{
 "title": "TestRunner API Dashboard",
 "tags": [
  "testrunner",
  "api",
  "monitoring"
 ],
 "time": { "from": "now-2h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "http_endpoint", "label": "HTTP endpoint" }
  ]
 },
 "panels": [
  {
   "title": "Host System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes-node_memory_MemAvailable_bytes",
     "legendFormat": "System CPU Usage"
    }
   ]
  },
  {
   "title": "TestRunner Container",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"testrunner-api\"}[$__rate_interval]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_working_set_bytes{job=\"testrunner-api\"}",
     "legendFormat": "Memory Usage"
    }
   ]
  },
  { "title": "TestRunner HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Endpoint Stat for range",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_route) (increase(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\".*$http_endpoint.*\"}[$__range]))) > 0",
     "legendFormat": "{{http_route}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, http_route) (increase(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\".*$http_endpoint.*\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, http_route) (increase(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\".*$http_endpoint.*\"}[$__range]))) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(sum by(le, http_route) (increase(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_response_status_code=\"408\", http_route=~\".*$http_endpoint.*\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TestRunner HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(le, http_route) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_count{http_route=~\".*$http_endpoint.*\"}[$__rate_interval])) > 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  },
  {
   "title": "TestRunner 99 HTTP Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, http_route) (rate(microsoft_aspnetcore_hosting_http_server_request_duration_bucket{http_route=~\".*$http_endpoint.*\"}[$__rate_interval]))) > 0",
     "legendFormat": "{{http_route}}"
    }
   ]
  }
 ]
}